const preloader=document.getElementById('preloader');addEventListener('load',()=>setTimeout(()=>preloader.classList.add('hide'),500));
const nav=document.getElementById('nav'),progress=document.getElementById('progress'),glow=document.querySelector('.cursor-glow'),heroBg=document.querySelector('.hero-bg');
function scrollUI(){nav.classList.toggle('scrolled',scrollY>40);const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%';heroBg.style.transform=`scale(1.08) translateY(${Math.min(scrollY*.06,45)}px)`}addEventListener('scroll',scrollUI,{passive:true});scrollUI();
addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';if(innerWidth>980){const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*-8;document.getElementById('tiltCard').style.transform=`perspective(1000px) rotateY(${x}deg) rotateX(${y}deg)`}});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');menuBtn.onclick=()=>{mobileMenu.classList.toggle('open');document.body.classList.toggle('menu-open');menuBtn.textContent=mobileMenu.classList.contains('open')?'✕':'☰'};
document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});mobileMenu.classList.remove('open');document.body.classList.remove('menu-open');menuBtn.textContent='☰'}});
document.querySelectorAll('.magnetic').forEach(b=>{b.onmousemove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`};b.onmouseleave=()=>b.style.transform=''});
document.getElementById('contactForm').onsubmit=e=>{e.preventDefault();document.getElementById('formMessage').textContent='Thank you! Your travel request has been received.';e.target.reset()};
